/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PalDashboardRouteImport } from './routes/pal-dashboard'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PalPalIdRouteImport } from './routes/pal.$palId'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as ApiPublicSeedDemosRouteImport } from './routes/api/public/seed-demos'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PalDashboardRoute = PalDashboardRouteImport.update({
  id: '/pal-dashboard',
  path: '/pal-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalPalIdRoute = PalPalIdRouteImport.update({
  id: '/pal/$palId',
  path: '/pal/$palId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemosRoute = ApiPublicSeedDemosRouteImport.update({
  id: '/api/public/seed-demos',
  path: '/api/public/seed-demos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chats': typeof ChatsRoute
  '/pal-dashboard': typeof PalDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wallet': typeof WalletRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/pal/$palId': typeof PalPalIdRoute
  '/api/public/seed-demos': typeof ApiPublicSeedDemosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chats': typeof ChatsRoute
  '/pal-dashboard': typeof PalDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wallet': typeof WalletRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/pal/$palId': typeof PalPalIdRoute
  '/api/public/seed-demos': typeof ApiPublicSeedDemosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/chats': typeof ChatsRoute
  '/pal-dashboard': typeof PalDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wallet': typeof WalletRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/pal/$palId': typeof PalPalIdRoute
  '/api/public/seed-demos': typeof ApiPublicSeedDemosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chats'
    | '/pal-dashboard'
    | '/profile'
    | '/reset-password'
    | '/wallet'
    | '/chat/$conversationId'
    | '/pal/$palId'
    | '/api/public/seed-demos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chats'
    | '/pal-dashboard'
    | '/profile'
    | '/reset-password'
    | '/wallet'
    | '/chat/$conversationId'
    | '/pal/$palId'
    | '/api/public/seed-demos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/chats'
    | '/pal-dashboard'
    | '/profile'
    | '/reset-password'
    | '/wallet'
    | '/chat/$conversationId'
    | '/pal/$palId'
    | '/api/public/seed-demos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ChatsRoute: typeof ChatsRoute
  PalDashboardRoute: typeof PalDashboardRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WalletRoute: typeof WalletRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  PalPalIdRoute: typeof PalPalIdRoute
  ApiPublicSeedDemosRoute: typeof ApiPublicSeedDemosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pal-dashboard': {
      id: '/pal-dashboard'
      path: '/pal-dashboard'
      fullPath: '/pal-dashboard'
      preLoaderRoute: typeof PalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pal/$palId': {
      id: '/pal/$palId'
      path: '/pal/$palId'
      fullPath: '/pal/$palId'
      preLoaderRoute: typeof PalPalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demos': {
      id: '/api/public/seed-demos'
      path: '/api/public/seed-demos'
      fullPath: '/api/public/seed-demos'
      preLoaderRoute: typeof ApiPublicSeedDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ChatsRoute: ChatsRoute,
  PalDashboardRoute: PalDashboardRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WalletRoute: WalletRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  PalPalIdRoute: PalPalIdRoute,
  ApiPublicSeedDemosRoute: ApiPublicSeedDemosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
